spring:



  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/information?useUnicode=true&characterEncoding=utf8
    username: root
    password: 111111
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: 127.0.0.1
    port: 6379
    password: 111111
    jedis:
      pool:
        max-active: 64
        max-idle: 10
        min-idle: 2
        max-wait: -1

